import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  patternsSidebar: [
		{
			type: 'doc',
			id: 'general/intro', // document ID
			label: 'Considerations', // sidebar label
		}, {
			type: 'doc',
			id: 'general/intro', // document ID
			label: 'Topologies', // sidebar label
		}, {
			type: 'doc',
			id: 'general/intro', // document ID
			label: 'Stakeholders', // sidebar label
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Patterns', // sidebar label
			link: {
        type: "doc",
				id: 'patterns/intro', // document ID
			},
			collapsible: false,
			items: [
				{
					type: 'category',
					label: 'Transfer Liquidity',
					items: [
						'patterns/intro',
					],
				}, 
			]
		},
  ],

};

export default sidebars;
