import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  stackSidebar: [
		{
			type: 'doc',
			id: 'stack/intro', // document ID
			label: 'Getting started', // sidebar label
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
			type: 'doc',
			id: 'stack/baseline', // document ID
			label: 'Baseline', // sidebar label
		}, {
			type: 'doc',
			id: 'stack/compose', // document ID
			label: 'Compose Layer', // sidebar label
		}, {
			type: 'doc',
			id: 'stack/interop', // document ID
			label: 'Interop Layer', // sidebar label
		}, {
			type: 'doc',
			id: 'stack/abstractionLayer', // document ID
			label: 'Abstraction Layer', // sidebar label
		}, 
  ],
  valueSidebar: [
		{
			type: 'doc',
			id: 'value/intro', // document ID
			label: 'Getting started', // sidebar label
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
			type: 'doc',
			id: 'value/memecoins', 		// document ID
			label: 'Memecoins', 			// sidebar label
		},{
			type: 'doc',
			id: 'value/reputokens', 	// document ID
			label: 'Reputokens', 			// sidebar label
		},{
			type: 'doc',
			id: 'value/utilities', 		// document ID
			label: 'Utility Tokens', 	// sidebar label
		},{
			type: 'doc',
			id: 'value/securities', 	// document ID
			label: 'Security Tokens', // sidebar label
		},{
			type: 'doc',
			id: 'value/stablecoins', 	// document ID
			label: 'Stablecoins', 		// sidebar label
		},{
			type: 'doc',
			id: 'value/crommodity', 	// document ID
			label: 'Crommodities', 		// sidebar label
		},
  ],
	valueChainSidebar: [
		{
			type: 'doc',
			id: 'valueChain/intro', // document ID
			label: 'Getting started', // sidebar label
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Tokenization', // sidebar label
			link: {
        type: "doc",
				id: 'valueChain/tokenization/intro', // document ID
			},
			collapsible: false,
			items: [
				{
					type: 'category',
					label: 'Tokenization Process',
					items: [
						'valueChain/tokenization/process/tokens/index',
						'valueChain/tokenization/process/tokenization-demand/index',
						'valueChain/tokenization/process/tokenization-supply/index',
						'valueChain/tokenization/process/tokenization-monetary-policy/index',
					],
				}, {
					type: 'category',
					label: 'Tokenization Models',
					items: [
						'valueChain/tokenization/models/asset/index',
						'valueChain/tokenization/models/asset-unbacked/index',
						'valueChain/tokenization/models/asset-utility/index',
						'valueChain/tokenization/models/asset-security/index',
						'valueChain/tokenization/models/asset-stablecoins/index',
						'valueChain/tokenization/models/asset-uoa/index',
						'valueChain/tokenization/models/asset-nft/index',
					],
				}, {
					type: 'category',
					label: 'Tokenization Utilities',
					items: [
						'valueChain/tokenization/utilities/utility/index',
						'valueChain/tokenization/utilities/utility-id/index',
						'valueChain/tokenization/utilities/utility-investment/index',
						'valueChain/tokenization/utilities/utility-currency/index',
					],
				}, {
					type: 'category',
					label: 'Tokenizable Assets',
					items: [
						'valueChain/tokenization/tokenomics/commodities',
					],
				}, {
					type: 'category',
					label: 'Tokenomics',
					items: [
						'valueChain/funding/allocations'
					],
				}, {
					type: 'doc',
					id: 'valueChain/tokenization/bibliography', // document ID
					label: 'Bibliography', // sidebar label
				},
			],
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Funding', // sidebar label
			link: {
        type: "doc",
				id: 'valueChain/funding/intro', // document ID
			},
			collapsible: false,
			items: [{
					type: 'category',
					label: 'Preparing Funding',
					link: {
						type: "doc",
						id: 'valueChain/funding/preparing/intro', // document ID
					},
					items: [{
							type: 'category',
							label: 'Prepare Documentation',
							items: [
								'valueChain/funding/preparing/roadmap',
								'valueChain/funding/preparing/whitepaper',
								'valueChain/funding/preparing/litepaper',
								'valueChain/funding/preparing/pitchdeck',
								'valueChain/funding/preparing/eMail',
							],
						}, {
							type: 'category',
							label: 'Perform Compliance',
							items: [
								'valueChain/principles/digital/compliance/funding/issuer',
								'valueChain/principles/digital/compliance/funding/HQ',
								'valueChain/principles/digital/compliance/funding/investors',
							],
						}, {
							type: 'category',
							label: 'Advertise your Project',
							items: [
								'valueChain/funding/advertising/watchers',
								'valueChain/funding/advertising/press',
								'valueChain/funding/advertising/agencies',
								'valueChain/funding/advertising/ambassador',
								'valueChain/funding/advertising/influencers',
							],
						}, {
							type: 'category',
							label: 'Build your Community',
							items: [
								'valueChain/funding/community/ama',
								'valueChain/funding/community/community',
								'valueChain/funding/community/users',
							],
						}, {
							type: 'category',
							label: 'Pitching Investors',
							items: [
								'valueChain/funding/pitching/incubators',
								'valueChain/funding/pitching/investors',
							],
						}, {
							type: 'category',
							label: 'Existing Launchpads',
							items: [
								'valueChain/funding/launchpads',
							],
						}, 
					],
				}, {
					type: 'doc',
					id: 'valueChain/funding/bibliography', // document ID
					label: 'Bibliography', // sidebar label
				}
			]
    }, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Negotiation', // sidebar label
			link: {
        type: "doc",
				id: 'valueChain/negotiation/intro', // document ID
			},
			collapsible: false,
			items: [/*{
					type: 'category',
					label: 'Deploying to Exchanges',
					items: [
						'valueChain/suite/dapp-admin/exchanges/exchanges-deploy-choose',
						'valueChain/suite/dapp-admin/exchanges/exchanges-deploy-dex',
						'valueChain/suite/dapp-admin/exchanges/exchanges-deploy-cex',
					],
				},*/ {
					type: 'category',
					label: 'Trading',
					items: [
						'valueChain/negotiation/trading',
					],
				}, {
					type: 'category',
					label: 'Monetary Policy',
					items: [
						'valueChain/negotiation/monetary',
						'valueChain/negotiation/stability',
					],
				}, {
					type: 'doc',
					id: 'valueChain/negotiation/bibliography', // document ID
					label: 'Bibliography', // sidebar label
				},
			]
    }, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Distribution', // sidebar label
			link: {
        type: "doc",
				id: 'valueChain/distribution/intro', // document ID
			},
			collapsible: false,
			items: [
				{
					type: 'category',
					label: 'Distribution Models',
					items: [
						{
							type: 'doc',
							id: 'valueChain/distribution/airdrops',
						}, {
							type: 'doc',
							id: 'valueChain/distribution/giveaways',
						}, {
							type: 'doc',
							id: 'valueChain/distribution/rounds',
						}, {
							type: 'doc',
							id: 'valueChain/distribution/operations',
						}, {
							type: 'doc',
							id: 'valueChain/distribution/rewards',
						}, 
					],
				}, {
					type: 'category',
					label: 'Token Operations',
					items: [
						'valueChain/distribution/operations',
					]
				}, {
					type: 'doc',
					id: 'valueChain/distribution/bibliography', // document ID
					label: 'Bibliography', // sidebar label
				},
			]
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'DeFi Services', // sidebar label
			link: {
        type: "doc",
				id: 'valueChain/defi/intro', // document ID
			},
			collapsible: false,
			items: [
				{
					type: 'category',
					label: 'Money',
					items: [
						'valueChain/defi/money/bibliography',
						'valueChain/defi/money/meanofexchange',
						'valueChain/defi/money/storeofvalue',
						'valueChain/defi/money/unitofaccount'
					],
				}, {
					type: 'category',
					label: 'Payments',
					items: ['valueChain/defi/payments/payments'],
				}, {
					type: 'category',
					label: 'Cards',
					items: ['valueChain/defi/cards/cards'],
				}, {
					type: 'category',
					label: 'Transfers',
					items: ['valueChain/defi/transfers/transfers'],
				}, {
					type: 'category',
					label: 'Lending',
					items: [
						'valueChain/defi/lending/lending',
						'valueChain/defi/lending/bibliography'
					],
				}, {
					type: 'category',
					label: 'Liquidity Provision',
					items: ['valueChain/defi/liquidity/liquidity'],
				},
			]
		}, {
      type: 'html',
      value: '<div class="border border-1 m-3" />',
		}, {
      type: 'category',
			label: 'Crowdsolving', // sidebar label
			link: {
        type: "doc",
				id: 'valueChain/crowdsolving/intro', // document ID
			},
			collapsible: false,
			items: [
				{
					type: 'doc',
					id: 'valueChain/crowdsolving/bibliography', // document ID
					label: 'Bibliography', // sidebar label
				},
			]
		},
  ],
  ecosystemSidebar: [
		{
			type: 'doc',
			id: 'ecosystem/ecosystem', // document ID
			label: 'Getting started', // sidebar label
		}, {
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Infrastructure', // sidebar label
			link: {
        type: "doc",
				id: 'ecosystem/dlts/intro', // document ID
			},
			collapsible: false,
			items: [
				{
					type: 'category',
					label: 'DLT Networks', // sidebar label
					link: {
						type: "doc",
						id: 'ecosystem/dlts/ecosystems/intro',
					},
					items: [
						'ecosystem/dlts/ecosystems/bitcoin',
						'ecosystem/dlts/ecosystems/ethereum',
						'ecosystem/dlts/ecosystems/modular',
					]
				}, 
				{
					type: 'category',
					label: 'Interoperability', // sidebar label
					link: {
						type: "doc",
						id: 'ecosystem/dlts/interop/intro', // document ID
					},
					items: [
						'ecosystem/dlts/interop/tools',
						'ecosystem/dlts/interop/patterns',
						'ecosystem/dlts/interop/services',
						'ecosystem/dlts/interop/ecosystem',
					]
				}, 
			]
		}, {
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Exchanges', // sidebar label
			link: {
        type: "doc",
				id: 'ecosystem/exchanges/intro', // document ID
			},
			collapsible: false,
			items: [
				'ecosystem/exchanges/list',
			]
		}, {
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Payments', // sidebar label
			link: {
        type: "doc",
				id: 'ecosystem/payments/intro', // document ID
			},
			collapsible: false,
			items: [
				'ecosystem/cards',
				'ecosystem/wallets/list',
			]
		}, {
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'DeFi Services', // sidebar label
			link: {
        type: "doc",
				id: 'ecosystem/defi', // document ID
			},
			collapsible: false,
			items: [
				'ecosystem/lending/intro',
				'ecosystem/transfers/intro',
			]
		}, 
	]

};

export default sidebars;
