import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  intercomSidebar: [
		{
			type: 'doc',
			id: 'intercom/intro',
			label: 'Intro',
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
			type: 'category',
			label: 'Trust Models',
			link: {
				type: "doc",
				id: 'intercom/trust/intro',
			},
			collapsible: true,
			items: [
				{
					type: 'category',
					label: 'Trusted',
					link: {
						type: "doc",
						id: 'intercom/trust/trusted/intro',
					},
					collapsible: true,
					items: [
						'intercom/trust/trusted/validation',
					]
				},
				{
					type: 'category',
					label: 'Trust Minimized',
					link: {
						type: "doc",
						id: 'intercom/trust/minimized/intro',
					},
					collapsible: true,
					items: [
						'intercom/trust/minimized/intro',
					]
				},
				{
					type: 'category',
					label: 'Trustless',
					link: {
						type: "doc",
						id: 'intercom/trust/trustless/intro',
					},
					collapsible: true,
					items: [
						'intercom/trust/trustless/verification',
					]
				},
			]
		}, {
			type: 'category',
			label: 'Agents',
			link: {
				type: "doc",
				id: 'intercom/agents/intro',
			},
			collapsible: true,
			items: [
				'intercom/agents/chains',
				'intercom/agents/relayers',
				'intercom/agents/validators',
				'intercom/agents/provers',
				'intercom/agents/routers',
				'intercom/agents/sequencers',
			]
		}, {
			type: 'category',
			label: 'Communication Patterns',
			link: {
				type: "doc",
				id: 'intercom/patterns/intro',
			},
			collapsible: true,
			items: [
				'intercom/patterns/messages',
				'intercom/patterns/mailbox',
				'intercom/patterns/execution',
			]
		}, 
  ],
  patternsSidebar: [
		{
			type: 'doc',
			id: 'patterns/intro',
			label: 'Requirements',
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, 
		{
			type: 'category',
			label: 'ERC-20 Standard',
			link: {
				type: "doc",
				id: 'patterns/erc20/intro',
			},
			collapsible: true,
			items: [
				'patterns/erc20/ecosystem',
				'patterns/erc20/scope',
			]
		}, 
		{
			type: 'category',
			label: 'State',
			link: {
				type: "doc",
				id: 'patterns/state/intro',
			},
			collapsible: true,
			items: [
				'patterns/state/storage',
				'patterns/state/value',
			]
		}, 
		{
			type: 'category',
			label: 'Patterns',
			link: {
				type: "doc",
				id: 'patterns/patterns/intro',
			},
			collapsible: true,
			items: [
				'patterns/patterns/bridge',
				'patterns/patterns/masterslavefixed',
				'patterns/patterns/masterslavevariable',
			]
		}, 
		{
			type: 'category',
			label: 'Issuer Use Cases',
			link: {
				type: "doc",
				id: 'patterns/issuer/intro',
			},
			collapsible: true,
			items: [
				{
					type: 'category',
					label: 'Token Design',
					link: {
						type: "doc",
						id: 'patterns/issuer/capture/intro',
					},
					collapsible: true,
					items: [
						'patterns/issuer/capture/captureutility',
						'patterns/issuer/capture/capturevalue',
					]
				}, 
				{
					type: 'category',
					label: 'Network Presence',
					link: {
						type: "doc",
						id: 'patterns/issuer/presence/intro',
					},
					collapsible: true,
					items: [
						'patterns/issuer/presence/creation',
						'patterns/issuer/presence/onboarding',
						'patterns/issuer/presence/rebalancing',
						'patterns/issuer/presence/withdrawing',
					]
				}, 
				{
					type: 'category',
					label: 'DeFi Services',
					link: {
						type: "doc",
						id: 'patterns/issuer/defi/intro',
					},
					collapsible: true,
					items: [
						'patterns/issuer/defi/exchanges',
						'patterns/issuer/defi/staking',
						'patterns/issuer/defi/lending',
					]
				}, 
			]
		}, 
		{
			type: 'category',
			label: 'Holder Use Cases',
			link: {
				type: "doc",
				id: 'patterns/holder/intro',
			},
			collapsible: true,
			items: [
				{
					type: 'category',
					label: 'Network Presence',
					link: {
						type: "doc",
						id: 'patterns/holder/presence/intro',
					},
					collapsible: true,
					items: [
						'patterns/holder/presence/moving',
					]
				}, {
					type: 'category',
					label: 'Operation',
					link: {
						type: "doc",
						id: 'patterns/holder/operation/intro',
					},
					collapsible: true,
					items: [
						'patterns/holder/operation/transfer',
						'patterns/holder/operation/swap',
					]
				}, {
					type: 'category',
					label: 'Retail',
					link: {
						type: "doc",
						id: 'patterns/holder/retail/intro',
					},
					collapsible: true,
					items: [
						'patterns/holder/retail/payments',
					]
				}, 
			]
		}, {
			type: 'category',
			label: 'Intends Use Cases',
			link: {
				type: "doc",
				id: 'patterns/intends/intro',
			},
			collapsible: true,
			items: [
				'patterns/intends/solvers',
			]
		}, 
  ],

};

export default sidebars;
